### ISSUE TITLE
it says module not found

### ISSUE THREAD

**Issue by actavislol** [verlox/VeyAPI#5]
**I contacted the owner and he said word for word "kys you slowfuck"**

**Comment by verlox** [comment]
you should take my advice skiddie

**Comment by actavislol** [comment]
> you should take my advice skiddie

no you fatass

**Comment by verlox** [comment]
ropemaxx rn

**Comment by actavislol** [comment]
> ropemaxx rn

ur the skid you hacked into my github to steal all my code you cunt

**Comment by verlox** [comment]
hows the veylib copy coming

**Comment by actavislol** [comment]
> hows the veylib copy coming

uhhhhh
